language: node_js
node_js: node

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    rooms:
      - wsu-ucomm:n2TLZRJd84rMOMbkKthSEMgS
    on_success: change
    on_failure: always
    on_start: never

branches:
  only:
    - master

before_script:
  - node --version
  - npm --version

script:
  - grunt default

before_deploy:
  - openssl aes-256-cbc -K $encrypted_602df1214139_key -iv $encrypted_602df1214139_iv -in .travis/a11y_deploy_rsa.enc -out .travis/a11y_deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/a11y_deploy_rsa
  - ssh-add .travis/a11y_deploy_rsa

deploy:
  skip_cleanup: true
  provider: script
  script:
    - rsync --rvzh --delete --exclude ".git" -e "ssh -i .travis/a11y_deploy_rsa" ./ www-deploy@wsuwp-indie-prod-01:/var/home/www-deploy/testing/
  on:
    all_branches: true
