language: node_js
node_js: node

cache:
  apt: true
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    rooms:
      - wsu-ucomm:n2TLZRJd84rMOMbkKthSEMgS
    on_success: change
    on_failure: always
    on_start: never

before_script:
  - node --version
  - npm --version

script:
  - grunt default
